[package]
name = "veristone"
version = "0.1.0"
edition = "2024"

[dependencies]
blif-parser = "0.1.7"
clap = { version = "4.5", features = ["derive"] }
petgraph = "0.8.3"
graphviz-rust = "0.9.6"
serde_json = "1.0.145"
serde = "1.0.228"
